# See:
# https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-maven
# https://central.sonatype.org/pages/apache-maven.html
# https://github.com/actions/setup-java

name: release

on:
  workflow_dispatch:

jobs:
  release:
    environment: maven_central
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Maven Central repository
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'zulu'
          # See https://central.sonatype.org/publish/publish-portal-maven/
          server-id: central
          server-username: CENTRAL_USERNAME # env variable to use for username in release
          server-password: CENTRAL_PASSWORD # env variable to use for password in release
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable to use for passphrase in release

      - name: Set up Git user
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Release
        run: |
          mvn -B -Dusername=${{ secrets.GH_USERNAME }} -Dpassword=${{ secrets.GH_ACCESS_TOKEN }} release:prepare
          mvn -B release:perform
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
